title: GoBusiness32
url: "https://covid.gobusiness.gov.sg" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  documentation:
    output: true

favicon: /images/favicon-GoBiz.ico

##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
#baseurl: "" # the subpath of your site, e.g. /blog
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
description: test test
#twitter_username: jekyllrb
#github_username:  jekyll







# Build settings
#markdown: kramdown
#remote_theme: isomerpages/isomerpages-template
#remote_theme: isomerpages/isomerpages-template@next-gen-ally-fixes
#safe: false

#plugins:
#  - jekyll-feed
#  - jekyll-assets
#  - jekyll-sitemap

# Breadcrumbs
#breadcrumbs:
#  root:
#    hide: false  # show breadcrumbs on root/home page
#    image: false # Show image or title text

# Resource Room and Pagination
#resources_name: "Media"
#paginate: 12
#paginate_path: "/Media/page:num"

# Homepage sections
#homepage_hero_i_want_to: false
#homepage_programmes: false
#homepage_resources: false

# Feedback Form URL
#feedback_form_url: false

# FAQ URL
#faq_url: /faq/
#faq_url_external: false

# Custom CSS file path
#custom_css_path: "/misc/custom.css"
#custom_print_css_path: "/assets/css/print.css"

#exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]

#collections:
#  list-of-e-services:
#    output: true
#  products-and-services:
#    output: true
#  documentation:
#    output: false
#  services:
#    output: false
#  opportunities:
#    output: false
#  psg:
#    output: false
#  government-assistance:
#    output: false
#  guided-journeys:
#    output: false
#  resources:
#    output: false
#  financial:
#    output: false
#  business-guides:
#    output: false
#  who-we-are:
#    output: false